### ISSUE TITLE
lost songs

### ISSUE THREAD

**Issue by milkyjoe2** [Nosskirneh/Apace-public#3]
first off, i wish there was a clear explanation for how to use the tweak in the first place... took me much longer than i wanted to figure out that i had to press and hold .. .. *on the song name*  to bring up apace controls. 

second, i know it's only one step to get there, by pressing and holding on the song name but  i really really wish i just could add the repeat, repeat 1 and shuffle buttons straight to the music player in Control centre.... it's something i would use so often that it's an issue for me.

third, while trying to figure out how to use the tweak, i managed to watch 3 of my songs disappear from my phone... not even realising whath the 'library' button did, no explanation of it anywhere... now itunes says they are on my phone but my music app and siri say otherwise. i cannot get them back , even after i uninstalled apace2 and rebooted. can you help me get them back?

**Comment by Nosskirneh** [comment]
Hi! I'm sorry to hear that Apace 2 wasn't what you expected.

> The buttons are presented when holding down on the now playing widget, either at lockscreen or in Control Center. Simply drag the finger to the desired action and release.

This explanation is what it says at Packix. It doesn't have to be on the song name, it could be anywhere on the widget. I tried hard for **several weeks** to get the buttons to show up like in the initial Apace (iOS 10). However, I couldn't figure it out at that time, and that's why I went for this solution instead. 

Sure, I probably could explain a lot better how to use Apace 2 and what each action does, but people tend to ignore reading long explanations and 'just get on with it'.

As for your songs, I'm terribly sorry to hear that happened. I don't use the Music app myself. Are these local tracks synced from iTunes or are they Apple Music synced tracks? You should be able to download/sync them again.

**Comment by milkyjoe2** [comment]
thank you for the reply. the tracks are synced from itunes on my computer, just raw mp3 files, i have a rule setup to sync any song with higher than 3 play count and these songs are either in that category or manually added to a synced playlist. i don't use apple music.

i have of course tried to resync the music from itunes and even to manually add the tracks to my phone by dragging and dropping, as normal songs do

**Comment by milkyjoe2** [comment]
i'm sorry i missed the explanation in the packix page, that one is on me. i was only looking within the tweak for the instructions.

also, i'm sorry and appreciate that you spent all that time trying to get the controls to appear at the initial widget. however i am finding the system in apace as it stands to be quite a drag to use. if i want to toggle repeat, repeat one and repeat off, i have to double tap every single time, and that excludes my dislike of having to bring up the apace option toggles by tap and hold.  i have to request a refund and it brings me no pleasure in doing it because either way i appreciate the time and effort you put into it.

**Comment by milkyjoe2** [comment]
on second thoughts. just keep the money. i don't need it and you deserve it for your work regardless. cancel the refund request i put through.

**Comment by milkyjoe2** [comment]
i found a fix for the missing songs. i removed the *playlist* which the songs were in from my iphone via itunes by desyncing that playlist, then re-added the playlist to synced playlists again. :)

**Comment by Nosskirneh** [comment]
I agree wholeheartedly – I am not entirely happy with the system either. Maybe I'll do a partial rewrite and change it.

I'm grateful for your kindness. However, I wouldn't want anyone to pay for something they won't be using. As such, I've of course refunded you. I'm glad you were able to solve the lost tracks!
