### ISSUE TITLE
Buttons not aligned. Latest Spotify 8.5.7 . Showing at bottom.

### ISSUE THREAD

**Issue by blinktactics** [Nosskirneh/Apace-public#6]
Bug with latest Spotify? 8.5.7? My buttons are showing at the bottom on lockscreen. "Bottom box side". Format is off? Or maybe just me ?

**Comment by Nosskirneh** [comment]
Closing due to solved in a [reddit thread](http://www.reddit.com/r/jailbreak/comments/bawrv4/releasebeta_apace_3_beta_ios_12_add_the_current/erysr0g).
